---
language: java
sudo: false
script: mvn clean verify

deploy:
   provider: cloudfoundry
   username: 
    secure: "OFcEa4pfe7zeVCizDq9UXeAb39wpFpFPgZeYUhbwnTbYMTSugwG7FT2syeJVnqP2KXobbo+Bv/mjS0tRRR9E9WeADxYwZKJM8kcTqhQmr4XXVuEgVH7aORQ+novXocLuyXTE3VHWrTAwX86rz+6qByHi/5b4YvIG+Oa3L0dQ/iPV7PmhuTZXn1jkS/owQlEAbD1WVGJajo9aIofxxJUesGTfGkI5/kEjN9cj7l12Xcgy2VH0dpkgOpGfvSyivK9EK8NrZHgkFS19PJA8njZ0JLWtEhQ4QfBI71YBF6IdsK+NylIL53vPpHVPRrz+px7OAVxxNfjc2DE25IRxvNltV/oUQrNIdsQfEmASzzkWUIZ70mJ3683F/08m5wb/0pCXP8b2Ead45mw89koKbnMv2vE3l+3SA/umM4iU6Rmf69YNGjbmjV4rYOL5HUBVIyx9rexP3K9VMz66mRaN7whm3HRNG4KHGPgg2ouLcSzdJP6PSpU8L6x1hMu1bP2CkErM3JUYrDH+KAuBJgTOljMfD4YRZfkn2FlHwsuFnf0jXzQYoK+W0vfcIQvnp7N4mE1KZd6ux/DKNWQAJV8IdcUR/bNAFgDk9qr9RXAgDgU62LBLxw95OQIUIlkZcLo3b9y/tXxP0EDeEs256thvlNSCyu4T/ZgnBbTE5fS55hOhBkQ="
   password:
    secure: "w5vvOBo/vv0yiM4z8VQb6LSAXezA60w129DJhver+Snk/F/2kvCtP6Gi95X1v0evCpAHj0Zsk2TLO/iILaibkvhQ5FoMMDLeQ6TUkjE57tMdbbff98MfYJyKdd5PHHShL74OK364whAIi3FaVvDQiS66VMGcF7RFENHwmmEeNLRTZpl1niENym+KEriunr2ZmmQHcfSlShXhg4oSzN1F8hhi7gvaqb1vAyBKY+0HAEQDKZdpSBov1ZIzAU1gkqRSa+F1qW/A3A2dLTUuRkSo2nbhKCCDNdQ8ro9laqOxqNqPArCFvjvpOqN/VYPf4/xRBkKJ0yATCELfyCUW3DaGiQ2M7SlmeM67Ud1/pkvRMGR3Nni/WnnL9Jdgdz0UlytzGBRmaSQ7tI/AHzTXng6QdP4P6dT1AjrHNOzq+G6Y9WiESB5O2QI/zAbPnp4heDQTyeGE2dfRIAfPB2EQq9PlEseVKeujDJPWMNBksUEhNcRCSYAx55qsu77IxDixL0egk6SYq6+eoth17muNyx9UWwfQ6IGOk58wo9DRMSDbnXfuu/uf1zzeawt08xRmLJmzYV1MflVEdIIFexgO+R67q7Vatq3cVDZnUrAywq0kktifQ9ET1HWKgtMpZWhoLtWdwDJKlxOQsS1HrDhh2YvifnyHn6SkPo+2f7kE9SHxMTc="
   api: https://api.run.pivotal.io
   organization: rfernandezv
   space: development